### ISSUE TITLE
Error when processing the "url" field of RS_2022-08 and RS_2022-09

### ISSUE THREAD

**Issue by Flopblopper** [Watchful1/PushshiftDumps#20]
I am able to use the combine_folder_multiprocess script on the "selftext" field, but trying to match on the "url" field of RS_2022-08 and RS_2022-09 results in the following error:

WARNING: File failed /submissions/submissions/RS_2022-08.zst: 'NoneType' object has no attribute 'lower'

**Comment by Watchful1** [comment]
Fixed. Redownload the script and it should handle those lines properly.

I'm not really sure why some submission objects don't have a url field, but evidently they don't. If it turns out that a lot of them don't, you might have to pass in `--error_rate 100` or some other percentage so it the rest of the lines go through correctly.
